language: rust
rust:
  - nightly

script: |
  cargo build --verbose &&
  cargo test  --verbose &&
  cargo doc   --verbose

cache: cargo

matrix:
  include:
    - rust: nightly-2018-01-12
      env: # use env so updating versions causes invalidation
        - CLIPPY_VERSION=0.0.179
      before_script:
        - rustup component add rustfmt-preview
        - cargo install clippy --version $CLIPPY_VERSION
      script:
        - cargo fmt -- --write-mode=diff
        - cargo clippy -- -D clippy
